### ISSUE TITLE
Error during load

### ISSUE THREAD

**Issue by Krisalexroberts** [kevinatown/MMM-Screencast#1]
Followed instructions to install, however it doesnt seem to load:

0|mm       | App threw an error during load
0|mm       | /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:60
0|mm       | };
0|mm       |  ^
0|mm       | SyntaxError: Unexpected token ;
0|mm       |     at Object.exports.runInThisContext (vm.js:78:16)
0|mm       |     at Module._compile (module.js:543:28)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:2:14)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:20:3)
0|mm       | Whoops! There was an uncaught exception...
0|mm       | /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:60
0|mm       | };
0|mm       |  ^
0|mm       | SyntaxError: Unexpected token ;
0|mm       |     at Object.exports.runInThisContext (vm.js:78:16)
0|mm       |     at Module._compile (module.js:543:28)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:2:14)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:20:3)

**Comment by kevinatown** [comment]
Hi there, sorry about this issue. I wasn't quite ready for this module to be released, still working on some bugs. Can you try and pull the newest version like so: 
`cd  /home/pi/MagicMirror/modules/MMM-Screencast/`
`git pull`
`npm install`

So at what point in the installation did this happen?

Also, did this happen during stating the MM, connecting your phone to your MM, or some other point in the process?

Thanks!

**Comment by Krisalexroberts** [comment]
I know :) I have been waiting for this for a while so as soon as I noticed it on Github, i thought I'd try it out!

I've pulled the latest version and I get the same error, installation is fine, when I start the MagicMirror service i get the error and a blank screen

`/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:20:3)
0|mm       | /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:60
0|mm       | };
0|mm       |  ^
0|mm       | SyntaxError: Unexpected token ;
0|mm       |     at Object.exports.runInThisContext (vm.js:78:16)
0|mm       |     at Module._compile (module.js:543:28)
0|mm       |     at Object.Module._extensions..js (module.js:580:10)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:2:14)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js:20:3)`

**Comment by Krisalexroberts** [comment]
I think I worked it out, you need an extra curly bracket on row 60 instead of a semi colon :)

**Comment by kevinatown** [comment]
You're right, the Hulu declaration was missing the final `}`. If you pull master it should be good!

Thanks, for bringing this issue to my attention!
