### ISSUE TITLE
Screencast loads with no errors, but does not appear

### ISSUE THREAD

**Issue by AndyC3108** [kevinatown/MMM-Screencast#10]
Hi Kevin

Apologies for contacting you, but I hope you can help.

I have a similar problem to another user, whereby the application seems to load OK in Magic Mirror, but I cannot cast to it.  I have tried 2 devices but the same thing happens.  I don't even get the video player to appear on screen.  My tablet or phone just eventually times out being unable to connect.  I have tried moving the script to different locations within the Magic Mirror config.js script, but it makes no difference.

I have also created the netStat.txt, topCPU.txt and topMemory.txt as you suggested in another post, but don't really know what to look for to be honest.

Hope you can help and many thanks in advance...

Kind regards

AndyC

**Comment by dan89eu** [comment]
Hi Kevin,
I have the exactly same issue.
Here is my output:
`npm start

> magicmirror@2.2.2 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.2.2
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Screencast
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-Screencast
Sockets connected & modules started ...
Launching application.
DIAL Server is running on PORT 8569
screencast stdout: 
> magicmirror-screencast@0.0.1 start /home/pi/MagicMirror/modules/MMM-Screencast
> electron app.js "http://www.youtube.com/tv?pairingCode=92529BA2-BC78-4821-A06D-34E71080E6E2&rUrl=ws%3A%2F%2F192.168.1.5%3A52246%2F8F772443-EA6B-40C8-A167-C1A92E8269FE&rId=0AEDE207-1D5A-4FCD-A92C-76D78A3380EE&theme=cl" "bottomRight" "500" "300"


screencast stdout: Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.screenCastWindow

screencast stdout: starting server on  /tmp/app.screenCastWindow 

screencast stdout: starting TLS server false

screencast stdout: starting server as Unix || Windows Socket
`

Thanks,
Dan

**Comment by kevinatown** [comment]
Hey Dan and AndyC, Sorry about all of the issues. I think some of the packages might have updated and I haven't had the time yet to update MMM-Screencast yet. I'll look into that. 

In the meantime: 

Dan - 
- Are you on a windows machine? 
- Is there any other info past that log you pasted?

AndyC - 
- If you post those files in this chat I can give a look over them and see whats up.

Thanks and hold tight! Im going to try and get to this as soon as possible!!

- Kevin

**Comment by AndyC3108** [comment]
Hi Kevin

Many thanks for the quick reply & please find attached files as requested.

Kind regards

AndyC

[netStat.txt](https://github.com/kevinatown/MMM-Screencast/files/1766161/netStat.txt)
[topCPU.txt](https://github.com/kevinatown/MMM-Screencast/files/1766162/topCPU.txt)
[topMemory.txt](https://github.com/kevinatown/MMM-Screencast/files/1766163/topMemory.txt)

**Comment by kevinatown** [comment]
Hi AndyC, sorry completely misread your previous message. Can you actually run:

```
display=:0 npm start >> log.log
```

Attempt to cast to your pi, wait a couple seconds, stop the app, and send me that log?

Thanks!
Kevin

**Comment by dan89eu** [comment]
Hi Kevin,

I'm on mac, the log is from my pi. Today I did a new test with with a fresh install (new sd card, latest raspbian, fresh install of magic mirror (only default modules)) and the same thing happens. 

Thanks! You're doing a great job!
Dan

**Comment by AndyC3108** [comment]
Hi Kevin

Thanks again for the quick response.  Please find attached log file as requested.

Cheers

Andy

[log.log](https://github.com/kevinatown/MMM-Screencast/files/1770569/log.log)

**Comment by bimbim2401** [comment]
i have the same issue on raspberry PI 3 with the last version of magic mirror.

**Comment by kevinatown** [comment]
So everything looks fine, at all of the logs y'all are showing me. I have another question do you hear any audio and just can't see the video?

**Comment by kevinatown** [comment]
Also can you send me a copy of your `config.js`?

**Comment by AndyC3108** [comment]
Hi Kevin

There is no audio or video.  When I try to connect (using my tablet or phone) it just says connecting to 'device-name' and that's all it does until it eventually times out.

I have attached my config file (with personal & security info removed).  Also changed file extension to 'txt' so I can upload it...

Many thanks again for you help...

Andy

[config.txt](https://github.com/kevinatown/MMM-Screencast/files/1782476/config.txt)

**Comment by bimbim2401** [comment]
Same for me no audio and no video

**Comment by Krijbolder** [comment]
follow...... I've the same problem. Config .js is the same as Andy.

**Comment by kevinatown** [comment]
Hi @AndyC3108 @bimbim2401 @dan89eu @Krijbolder,

So it looked like the newer version of electron wasn't loading the URL as it should, I reverted the version to an older version until I can look into why (I think it might have to do with chrome vs. chromium). 

Anyways, please try updating the following and letting me know if it works for y'all:

```
# from the MagicMirror dir
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
```
Then try running the app again.

Thanks,
Kevin

**Comment by Krijbolder** [comment]
Hi Thanks Kevin,Executed, but the iphone does not recognize the raspberry anymore. the icon to share is no longer visible.Op 7 maart 2018 om 19:36 schreef Kevin Townsend <notifications@github.com>:  Hi @AndyC3108 @bimbim2401 @dan89eu @Krijbolder,So it looked like the newer version of electron wasn't loading the URL as it should, I reverted the version to an older version until I can look into why (I think it might have to do with chrome vs. chromium).Anyways, please try updating the following and letting me know if it works for y'all:# from the MagicMirror dir
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
Then try running the app again.Thanks, Kevin—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kevinatown** [comment]
@Krijbolder Hi Ben, sorry I had a typo in `DialServer.js`, try the steps again. Also make sure you stop the MagicMirror before doing these:
```
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
```
Also sometimes it takes a bit of time for the phone to find the dial server. Let me know how it goes.
Kevin

**Comment by Krijbolder** [comment]
I'm sorry It works!!!Thanks for your help!! grtz BenOp 7 maart 2018 om 19:36 schreef Kevin Townsend <notifications@github.com>:  Hi @AndyC3108 @bimbim2401 @dan89eu @Krijbolder,So it looked like the newer version of electron wasn't loading the URL as it should, I reverted the version to an older version until I can look into why (I think it might have to do with chrome vs. chromium).Anyways, please try updating the following and letting me know if it works for y'all:# from the MagicMirror dir
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
Then try running the app again.Thanks, Kevin—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Krijbolder** [comment]
It works for me!! Thanks Kevin!!!

**Comment by AndyC3108** [comment]
Hi Kevin

All working now!

Many thanks & best wishes....

Andy

**Comment by dan89eu** [comment]
Hi Kevin
You're the best! It's working perfect!

Thanks,
Dan

**Comment by kevinatown** [comment]
Wonderful. I'm closing this issue.
