### ISSUE TITLE
Video connects and plays, but I can't disconnect

### ISSUE THREAD

**Issue by treyg** [kevinatown/MMM-Screencast#102]
If a video is playing, if I lock my phone or switch apps, I have no way of reconnecting to do stop the video and am forced to restart the mirror. 

Any ideas?

I'm on a raspberry pi 4. 

Thanks!

**Comment by pprayoga** [comment]
Hi, is it possible that you are using remote desktop to open the Magic Mirror? Because I got the same problem while running the magic mirror through remote desktop for my PI.

**Comment by treyg** [comment]
> Hi, is it possible that you are using remote desktop to open the Magic Mirror? Because I got the same problem while running the magic mirror through remote desktop for my PI.

Hmm interesting. I thought I've tried it both ways. I'll double check though. I'm running my pi directly to a monitor, then just starting the mirror with a Bluetooth mouse app on my phone. I have done it from ssh though, so I'll check again and make sure that's not it. Thanks!

**Comment by pprayoga** [comment]
> > Hi, is it possible that you are using remote desktop to open the Magic Mirror? Because I got the same problem while running the magic mirror through remote desktop for my PI.
> 
> Hmm interesting. I thought I've tried it both ways. I'll double check though. I'm running my pi directly to a monitor, then just starting the mirror with a Bluetooth mouse app on my phone. I have done it from ssh though, so I'll check again and make sure that's not it. Thanks!

I got mine working just fine and I could control the screen cast from my phone. I try run the mirror without remote desktop, try that and let me know if it's working.
![IMG_4773](https://user-images.githubusercontent.com/68753270/105361201-09f06d00-5c2c-11eb-85fc-537d9dc6d215.jpeg)

**Comment by treyg** [comment]
> I got mine working just fine and I could control the screen cast from my phone. I try run the mirror without remote desktop, try that and let me know if it's working.

Seems to be fine now. Thank you! I'm be sure not to remote in. I also upgraded my internet, which seemed to help.
