### ISSUE TITLE
Casting not discovered across VLANs

### ISSUE THREAD

**Issue by robertalexa** [kevinatown/MMM-Screencast#114]
Hi @kevinatown 

I have a bit of a weird one, and I have been trying everything that i could think off, but to no avail. I was hoping that maybe I can describe this to you and see if you have any thoughts.

My Mirror is sitting on an IoT vlan. If I go on Youtube in the broser of the host rpi, I can cast without issues. However the casting is not available in my main VLAN.

I do indeed have firewall rules to restrict communications between VLANs but I do have exceptions for certain ports. My Chromecast devices function properly without issues.

To validate that this is not a firewall issue, I have disabled all the rules and that made no difference, I still can't find MM across VLANs to cast to.

Of course I have the right setup for IGMP Snooping, Multicast Enhancement etc, no difference.

Also, I can see the port being open from my main VLAN, which makes this even more weird
![image](https://user-images.githubusercontent.com/9019306/121246935-92993e00-c899-11eb-8a08-4f6831c8ad9f.png)

I can however confirm that your module was working fine in my old house, were my network was very basic with a regular consumer router, all devices in the same place. So I know that in principle your module is fine.

The only thing I can think of is that the module opens port 8569 on TCP6, and not TCP, or at least both
![image](https://user-images.githubusercontent.com/9019306/121246442-1272d880-c899-11eb-8078-47919b4598ff.png)

And I feel that my issue might be related - or I could be very wrong, at this point, i don't even know anymore.

Would it be possible to open the port as TCP instead? Should I raise this question with [peer-dial](https://github.com/fraunhoferfokus/peer-dial)?

Any thoughts?

Thanks in advance

**Comment by kevinatown** [comment]
@robertalexa sorry for the delay on this, but this is a good question.. The server that peer-dial uses nodes http module to connect to an address. 

> If host is omitted, the server will accept connections on the [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (::) when IPv6 is available, or the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (0.0.0.0) otherwise.

It seems like I can another config for you to specify the address to listen on, or better just default to the unspecified IPv4 address (which I just did). Let me know (after you pull/reinstall) if it still doesn't work.

**Comment by robertalexa** [comment]
@kevinatown Thanks for looking into this for me, much appreciated.

Just pulled and rebuild, the port seems to have opened up correctly, so what you did definitely worked.
![image](https://user-images.githubusercontent.com/9019306/152442050-c4deba05-e70f-469c-a50f-25456db93a8f.png)


Currently I am still not seeing the mirror as an available cast device but I am not yet jumping to conclusions, it might well be a propagation delay. So i will run with this for a bit, run some more tests and get back to you when i know more.

But thanks again for taking the time to look into it.

**Comment by kevinatown** [comment]
Wonderful! I'm glad it's at least being found on your other VLAN! MMM-Screencast can take a little time to actually come online, so it may be that. Let me know if theres any other way I can help!

Also, I'm closing this issue as the original request was fixed, but feel free to open another one or reopen this one if you have more qs!

**Comment by blackthroat** [comment]
@robertalexa Did you ever get this figured out? I can also successfully use AirPlay and Google Cast across multiple VLANs, however I'm not able to discover my magicmirror (RPi3B+), which is discoverable/castable on my LAN network.

**Comment by robertalexa** [comment]
Nope. but also not tried any more effort since the original post. just kinda left and forgot about it
