### ISSUE TITLE
Only works when not in server mode

### ISSUE THREAD

**Issue by zack949** [kevinatown/MMM-Screencast#12]
When MM is run in server mode and a remote client connects the video plays on the server, rather than the remote client,

**Comment by kevinatown** [comment]
Hey Zack,

Just curious what are you running the MM on? Also what do you mean it doesn't work in server mode? Finally, I had to update some dependencies so can you try:
```
# from the MagicMirror dir
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
```
Then try running the app again.

Thanks let me know how it goes.

**Comment by kevinatown** [comment]
I'm going to close this issue. Feel free to open another issue if you have any more problems.
