### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kikosilva17** [kevinatown/MMM-Screencast#121]
Hi, im having an issue trying to cast a video in youtube to my MM. It appears my device in the youtube cast, however keeps connecting and doesnt actually do nothing... can u help?

**Comment by kevinatown** [comment]
Hi @kikosilva17, can you please provide some more details and a log of the MagicMirror starting up, connecting to the screen-cast, waiting a bit, and then closing?

To provide a log you can simply do: 

```bash
display=:0 npm start >> log.log
```

thanks!

**Comment by kikosilva17** [comment]
Hey, thank you but already solved it ahaha working great... Great job and great module you got here!

**Comment by kevinatown** [comment]
wonderful thanks!
