### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by PrincesseLulu** [kevinatown/MMM-Screencast#13]
Hey, i have this error on windows.
I have test the windows branch but it's like as..

![sans titre](https://user-images.githubusercontent.com/18584249/37217778-bdb4f15c-23be-11e8-9b7d-ffb18460b76e.png)

Do you no why ? And why can i do for repair this ?
Thank you by advance !

**Comment by kevinatown** [comment]
Hi @PrincesseLulu, so the `windows` branch is old and should not be used. this issue was actually fixed on master and windows machines should now be supported. Please try the following:

```
cd modules/MMM-Screencast/
rm -rf node_modules/
git checkout master
git pull
npm install
```

Let me know if you have any other issues!
