### ISSUE TITLE
Breaks if connected to a bluetooth audio source.

### ISSUE THREAD

**Issue by DWOODNESS** [kevinatown/MMM-Screencast#14]
Looks like when my bluetooth headphones are connected to the PI, the screencast will load the video then freeze, you can mess with the window, change videos through the pi, but each video just pauses and won't play. disconnect bluetooth headphones, instantly plays.

**Comment by kevinatown** [comment]
Hey Doodness, 

Sorry about this issue. I haven't tried using it with bluetooth. Can you help by getting me some logs so I can see whats happening when you try running the app when using bluetooth. 

```bash
display=:0 npm start >> log.log
```

And in another terminal with the bluetooth, MM running, and casted to MMM-Screencast run:
```bash
netstat -lptn >> netstat.log
```

Then disconnect from the bluetooth so the video will play and then end the MM. Please add the two created log files and paste them here, that would be very helpful to find out whats going on. 

Thanks!

**Comment by DWOODNESS** [comment]
[netstat.log](https://github.com/kevinatown/MMM-Screencast/files/1850393/netstat.log)
[log.log](https://github.com/kevinatown/MMM-Screencast/files/1850394/log.log)


Here are the 2 logs requested. Looks like it's having a lot of issues, works perfectly if i'm connected via 3.5 or just not pushing sound at all.

**Comment by kevinatown** [comment]
Thanks for these logs. I definitely see quite a bit of errors and these logs will help me diagnose whats going on. Also what do you mean by: 'works perfectly if i'm connected via 3.5 or just not pushing sound at all'?

**Comment by DWOODNESS** [comment]
It means, if I'm connected via 3.5mm audio jack on the PI, it pushes sound to that and works with screencast, if I'm not connected to any sound source at all, aka no 3.5mm and no Bluetooth screencast works as well. It's just when I connect something Via Bluetooth it freezes and does nothing.

**Comment by kevinatown** [comment]
Hey @DWOODNESS so I hate to say this, but I believe this is a configuration problem with your bluetooth device/ALSA lib. I don't really have a bluetooth device that I'm using and don't have a good way to test this. I did find this: https://superuser.com/questions/273561/how-can-i-make-chromium-use-a-different-alsa-device don't know if it will be helpful. Pretty much what I think you need to do is to configure chromium to use a different audio out. I hope this is helpful.

**Comment by kevinatown** [comment]
Hey @DWOODNESS I am going to close this issue as it has gotten stale. Also some others users have found a solution to the sound issue requiring ALSA lib, here: https://github.com/kevinatown/MMM-Screencast/issues/18

Feel free to reopen it if you're still having this issue.
