### ISSUE TITLE
Cant see to get it working??

### ISSUE THREAD

**Issue by Sizer009** [kevinatown/MMM-Screencast#15]
I have followed the install instructions, no issues there but when I try and cast from PC or Phone the raspberry doesn't show up as an option so I have no idea how to get it to play a video. There is no place holder shown on magic mirror its just black were the videos are meant to appear.

**Comment by KairosZenith** [comment]
i had to do it from my computer first.  I got it working on my phone finally, but it never and still doesn't show in the "cast" menu from my phone's YouTube.  

The MMM Screencast  never seems to work on the first try (or even a few tries), but i start playing a YouTube video in my Chrome browser.  i then click on the Cast option on the video.  i just keep trying about every 10 to 20 seconds or so.  i see the cast icon on the right side of my address bar appear every time i click the Cast, but goes away until the time it actually works.  Every time it works, i see the icon stay and then it shows up on the Magic Mirror within several seconds.  

i want this to be easier then having to do the casting from my computer every time, so i hooked up the mouse to the Magic Mirror and stopped the video.  It takes a few seconds to find where the mouse is on the screen, especially if you have the video a small size.  i made the screen a lot bigger while i did this step.  Click: --"Go Back" then --"Settings" then  --"Link Another Device" if you didn't already see it. 

You'll see the options "Link with Wi-Fi" or "Link with TV Code" .... if you didn't see your Magic Mirror before, then the "Link with wifi" probably won't work here either, so you'll have to do "Link with TV code" like i did.  If you see a code with all letters, then it probably won't work.  That's what i got the first time i tried it.  You need the code that gives only numbers. 

Then open the YouTube App on your phone and go to "Settings" then "Watch on TV" .... Then you should be able to enter the code there.  On my computer, it showed up as "Magic Mirror" (casting device) but it shows up as "YouTube TV" on my phone. After going through all that trouble, i'm then able to control the YouTube videos from my phone.  i just wish it would close the video window after the video finishes.

**Comment by KairosZenith** [comment]
Also, i'm not for sure, but i think i saw something about having SSH on, will help.  i'm not certain on that, but just something i "thought" i read about troubleshooting with Screencast.  Although, most people doing this probably already have SSH on  :)

**Comment by kevinatown** [comment]
Hey y'all, 

@Sizer009 currently only YouTube casting from a mobile device is supported. I have not tested from a browser, however KairosZenith said he was able to get it from a browser. I have created it to not have have a placeholder so valuable screen space is not taken up. Also, it may take a couple of tries of pressing the casting button to get the MagicMirror(or whatever the name of the device you use) to show up in the casting option on your phone. I am aware that this is an issue and want to work on making the discovery aspect better.

@KairosZenith I am kinda confused about your issue. As I started earlier I am aware that sometimes the discovery aspect is a little slow and that I wish to fix it, however I am not sure what you mean by starting it on chrome and moving to your phone? Also SSH shouldn't have anything to do with it as SSH is generally on port 22 and this is on another port.

Finally, it would be helpful to see y'all's configs and some run logs to see if there are any issues there. To get the run logs please do:

```bash
display=:0 npm start >> log.log
```

Allow this to run for a bit and try a few times to find the MM in the youtube app in your phone.
