### ISSUE TITLE
Screencast Regions & Closing the Cast

### ISSUE THREAD

**Issue by KairosZenith** [kevinatown/MMM-Screencast#16]
Hey, thanks for the Magic Mirror Screencast module, cause i probably watch more YouTube than i do TV, lol.  i have my TV oriented in normal landscape mode and i was trying to centralize my YouTube video in the middle of my other modules.  The problem is that i had to adjust where "my" middle is because it's slightly over to the right because my module on the left is bigger than the modules on the right.  i think i adjusted the code to be 55% instead of 50%.  With Screencast having it's own defined regions, it's not centered with my clock i have.  i also want to put it next in line of my center region modules, but it just covers up my clock (the first module in the center).  So i'm just trying to find the code that defines where these regions are and hopefully be able to adjust it like i did my center region on Magic Mirror.  

The next issue is that it doesn't close out the window when i stop my YouTube cast.  i think i saw something about there only being certain closing commands.  i'm only lightly experienced with coding.  i am using a Raspberry Pi 3 with wifi on a TV (actual TV) and casting from a LG smartphone and even my computer using Google Chrome browser.   Thanks for all the time you put into this and any help you can give.  
![magicmirror01](https://user-images.githubusercontent.com/37647863/37871201-7dce705a-2fb6-11e8-8bb7-08873d3a3724.jpg)

**Comment by kevinatown** [comment]
Hey, can you provide a screenshot/image of exactly where you want the module to be positioned? Also you can try these positions: 
- trayLeft
- trayBottomLeft
- trayRight
- trayBottomRight
- trayCenter
- trayBottomCenter
- topLeft
- topRight
- bottomLeft
- bottomRight
- topCenter
- bottomCenter
- center 
and adjusting the size of MMM-Screencast. If these don't work I can see if I can change up the app and add a config for the exact screencast window.

For the second issue:
- When you close out of the cast do you disconnect on you phone?
- Can you run the app like this to get a log:
```bash
npm start >> log.log
```
Start the app, cast to the MM, try stoping the video and quitting the cast. Can you paste the log in here?

Thanks!

**Comment by KairosZenith** [comment]
For the issue on the position, i want to fit it right in the middle of everything, in that empty space on the picture in the first post.  The problem that's created is because the calendar module on the left are bigger (wider) than the modules on the right side, it causes my open center area to be shifted to the right of the screen's center line.  i can get the video to play in the middle of the screen, but that causes it to cover part of my schedule on the left side.  i need to shift the center position over just slightly.  i moved the original MagicMirror center over to 55% instead of the 50% that it had, that way my clock is "relatively centered" but it's not centered in the middle of the TV.  The "quotes" and "news" on the bottom is still actually centered in the middle of the TV. 

But ..... in all actuality ..... i probably wouldn't worry about the "relative" position of the video screen if it would close out after i'm done with the "cast." That way i could just fix that problem and not have to worry about the video position.

i just got through skimming through the Screencast folders and saw the "electron-positioner" & "src" folders might have something to do with the position? 

Also, my phone never see's the Magic Mirror, but my Chrome browser on my PC does.  If i start it from my PC and get it to pop up, i can then use my mouse and keyboard in the video box on the Magic Mirror to get a "cast" code so that i can use it on my phone.    i will work on getting that log for you sometime tomorrow.  Thanks again for your time.

**Comment by KairosZenith** [comment]
Today, i was going to get you that log, but when i tried it, i actually saw MagicMirror in the Cast list.  It never showed up on my phone before (on many tries).  It only showed up on my web browser on my PC.  Since it was showing up on my phone, i tried it and it started up like it should.  i watched a video for a few minutes and then stopped the Cast.  When i stopped the Cast, the module did what it was supposed to do .... close out :)  i didn't do anything different.  It's been off since the last i tried, yesterday.  Maybe the whole Pi needed to be turned off and rebooted, not just restarting MagicMirror in between, whatever change i made that fixed it.  Well, that issue seems good for the moment.

The other issue isn't as important, now that the Cast window closes out when i'm finished, yay :)  Although, i would still like to know how to move the Cast Window region over slightly, if i need to in the future.  Thanks again for the help.

**Comment by KairosZenith** [comment]
One other question, since it seems to be working OK for now .... i have the same Cast icon on my Netflix App.  Is there a way to cast it with Screencast or at least some small modifications to the App or is that going to be a big change to get that to work?

**Comment by kevinatown** [comment]
Hey Karios, glad to hear that your phone can find the MM now, I am aware that the discovery aspect is not the best and I would love to improve it. Also I will try to work on your positioning issue this week if, I can find time. I am thinking of adding another param that you would be able to add the coordinates of where you would like the video to pop up, so that you could have more freedom than using just the predefined locations.

As for your final comment, I am aware that the Pi shows up on Netflix, but I have not been able to get it working/get useful information from the connection. I think many companies have moved away from the DIAL to another protocol. I would like to revisit this when I find time and figure out away to allow for casting from other apps.

**Comment by Poolitzer** [comment]
hello there.

Just thought about commenting rather then making a new issue.

I would love to put that video a bit down. Just a bit. If I can use custom css class, I would be satisfied. Just tell me how. Or, as you wrote there, you can add it to the module directly? I don't know what is easier for you. But it would be great :)

Thanks for this otherwise amazing module, working without any problems for me.

**Comment by kevinatown** [comment]
Hey @Poolitzer when you say "put that video a bit down", I actually have an outstanding branch that allows you to position exactly where the video will be located on you screen. Unfortunately you cannot just add a css class to it as it is an independent electron app. I will try to get that branch merge in. However in the meantime you can check out that branch and read the README for configuring the exact location. It might not work as there was a reason I never merged it in...

**Comment by kevinatown** [comment]
Hi all this has been closed by #93, where a new config can be used to set the video to the exact location... didnt relize that there were other issues still open. sorry.
