### ISSUE TITLE
How to cast

### ISSUE THREAD

**Issue by Arkoxs** [kevinatown/MMM-Screencast#2]
Installation went without issues. No errors, the Magic Mirror restarted without problems after adding this module to the config.js. 
			module: 'MMM-Screencast',
			position: 'bottom_right',
			config: {
				position: 'topCenter',
				height: 300,
				width: 500,
			}

Nothing is displayed, how do I cast to this module? It does not register as a cast device on my network.

**Comment by kevinatown** [comment]
Hey! Sorry about the issues. Just some questions to help figure out what’s going on (some might seem stupid, but I have to ask). Do other modules open and work on you MM? Is your pi and phone connected to the same WiFi network? What are you trying to cast from (currently YouTube is only supported)? Can you paste the console log info in this chat?

Thanks!

**Comment by Arkoxs** [comment]
Hi, thanks for the quick response. I'll try to get the console log info later. 
The pi and my phone are on the same internal Wifi network, I'm trying to cast from the Youtube app on my android phone. All of the other modules are loading correctly.

**Comment by kevinatown** [comment]
Cool. You can run the MM with this command:
```
display=:0 npm start >> log.log
```
And a file in the MM directory called `log.log` will be created with all of the terminal output. Run this command and after the MM and all modules are loaded, open your youtube app. If you can send the contents of this log to me.

Thanks!

**Comment by Arkoxs** [comment]
Hi, I'm embarrassed to say that I've found what was wrong. The logs did not contain any errors so I decided to remove all other modules and just test it with MMM-Screencast,

It turned out that my FTP program kept skipping the config.js file so the new config was never uploaded. After correctly uploading the new config.js with the MMM-Screencast module section, the MagicMirror was immediately available as 'raspberrypi' in the Youtube screencast option.
The only issue now is the performance of my RPi 2.

Thank you so much for your time and effort.

Regards,

**Comment by kevinatown** [comment]
Great, I am glad you got it working! Yea, I haven't tested it on many different pi versions, only really on my Pi 2 Model B and it seems to work well. Do you have much else running on your Pi (other programs or many different modules that could be taking up network and cpu bandwidth)? Does it have a strong enough internet connection? Let me know if there is something else I can help you with in a new issue, as your original issue seems to be resolved. 

Good luck and enjoy your magic mirror and MMM-Screencast!

**Comment by rihardiii** [comment]
Hi, i ran the command you suggested and i get the errors like this:
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-14T07_32_43_647Z-debug.log

**Comment by rihardiii** [comment]
needless to say im running it from home folder..

**Comment by rihardiii** [comment]
sry ran it from MM folder and all was good.

    Starting MagicMirror: v2.4.1
    Loading config ...
    Loading module helpers ...
    No helper found for module: clock.
    Initializing new module helper ...
    Module helper loaded: calendar
    Initializing new module helper ...
    Module helper loaded: MMM-NowPlayingOnSpotify
    No helper found for module: currentweather.
    No helper found for module: weatherforecast.
    Initializing new module helper ...
    Module helper loaded: MMM-Screencast
    All module helpers loaded.
    Starting server on port 8080 ...
    Server started ...
    Connecting socket for: calendar
    Starting node helper for: calendar
    Connecting socket for: MMM-NowPlayingOnSpotify
    Connecting socket for: MMM-Screencast
    Sockets connected & modules started ...
    Launching application.
    Create new calendar fetcher for url: -_private URL here_-
    Create new calendar fetcher for url: -_private URL here_-
    Create new calendar fetcher for url: -_private URL here_-
    DIAL Server is running on PORT 8569
    Refreshed access token because it has expired. Expired at: 11:03:44 now is: 11:03:45
    Refreshed access token because it has expired. Expired at: 12:03:45 now is: 11:03:45
    Shutting down server...
    Stopping module helper: calendar
    Stopping module helper: MMM-NowPlayingOnSpotify
    Stopping module helper: MMM-Screencast

but it still looks like im not able to cast to the screen... maybe something with my internet connection

**Comment by rihardiii** [comment]
jup, all my problems were with internet connection.

**Comment by AdamStripz** [comment]
Hello, i'm having the same problem, here's the error after running display=:0 npm start >> log.log

A JavaScript error occured in the main process
Uncaught Exception
TypeError: Cannot read property 'substr' of undefined
  at Positioner._getCoords (/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron-positioner/index.js.85:20)
  at Positioner.move(/home/pi.MagicMirrorr/modules/MMM-Screencast/node_modules/electron-positioner/index.js.110:25)
  at App.<anonymous>(/home/pi.MagicMirrorr/modules/MMM-Screencast/app.js.50:14)
  at Object.onceWrapper (events.js:273:13)
  At App.emit (events.js:187:15)

Id love to try Arkoxs' fix but i think i have a bigger problem and there wasn't much on how he fixed it.
plz Any help would be awesome
-AdamStripz
