### ISSUE TITLE
when module code entered mirror wont load 

### ISSUE THREAD

**Issue by popycok** [kevinatown/MMM-Screencast#22]
hey i am very excited to use your module but i have entered the code into my config in a multitude of ways but every time i run magicmirror i get the config module error when i remove the code and revert back to my original setup  it works again,could you please insert the code correctly for me? i am a basic noob when it comes to this stuff /* Magic Mirror Config Sample
`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Events",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "removed for privacy"
					},
					{
						symbol: "MyCalendar ",
						url: "removed for privacy"
					},

					{
						symbol: "MyCalendar ",
						url: "removed for privacy"
					},
				]
			}
		},
		{
		  module: 'MMM-MyCommute',
		  position: 'bottom_right',
		  config: {
		    apikey: 'removed for privacy',
		    origin: 'removed for privacy',
		    startTime: '00:00',
		    endTime: '23:59',
		    hideDays: [0,6],
		    destinations: [
		      {
		        destination: 'removed for privacy',
		        label: 'removed for privacy',
		        mode: 'Driving',
		        color: '#82E5AA'
		      },
		      {
		        destination: 'removed for privacy',
		        label: 'removed for privacy',
		        mode: 'Driving'
		      }
		    ]
		  }
		},
		{
			module: "currentweather",
			position: "top_left",
			config: {
				location: "Calgary",
				locationID: "5913490",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "removed for privacy"
			}
		},
		{
			module: "weatherforecast",
			position: "top_left",
			header: "Weather Forecast",
			config: {
				location: "Calgary",
				locationID: "5913490",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "086e8fc9791b2ad93e7ee922e3dc772e"
			}
		},
 		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "CBC Calgary",
						url: "http://rss.cbc.ca/lineup/canada-calgary.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
			{
			  module: "MMM-NowPlayingOnSpotify",
			  position: "top_left",
			
			  config: {
			    clientID: "removed for privacy",
			    clientSecret: "removed for privacy",
			    accessToken: "removed for privacy"
			  }
},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by kevinatown** [comment]
Hi @popycok is this how your config file currently looks? if so you should be able to just add:
you can prob just add this:
```
{
		module: 'MMM-Screencast',
		position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
		config: {
			position: 'bottomRight',
			height: 300,
			width: 500,
		}
 }
```

To the end of it. Can you send me an example of how your config looks with your config in it?

**Comment by popycok** [comment]
Here is a example of what my config would look like,  and thank you for your help @kevinatown


  {
          module: "MMM-NowPlayingOnSpotify",
          position: "top_left",
        
          config: {
            clientID: "removed for privacy",
            clientSecret: "removed for privacy",
            accessToken: "removed for privacy"
          }
                 },
 
                 {
           module: 'MMM-Screencast',
           position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
           config: {
            position: 'bottomRight',
            height: 300,
            width: 500,
        }
 }

 ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by kevinatown** [comment]
I realized I never got the error. Can you put the exact output from running the app to the error in here, please?

**Comment by popycok** [comment]
so this is a the basic setup from the sample config that i added your code and i get these errors

```Line 91 col 1 Expected '}' to match '{' from line 11 and instead saw '{'.
Line 91 col 2 Missing semicolon.
Line 92 col 17 Label 'module' on MMM-Screencast statement.
Line 93 col 9 Expected an assignment or function call and instead saw an expression.
Line 93 col 17 Missing semicolon.
Line 93 col 9 Unrecoverable syntax error. (88% scanned).
```


```/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]
{
		module: 'MMM-Screencast',
		position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
		config: {
			position: 'bottomRight',
			height: 300,
			width: 500,
		}
 }

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by popycok** [comment]
this is the only way i can get it to work 

```/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",
								modules: [
						        






							{
								module: 'MMM-Screencast',
								position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
								config: {
									position: 'bottomRight',
									height: 300,
									width: 500,
								}
						        }
						    ]
						};
							
									

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by popycok** [comment]
I managed to get it working, went from a empty config file and added one module at a time fixing my code errors until I had them all working. And may I say your module is awesome! Thank you

**Comment by kevinatown** [comment]
Awesome! Glad you got it working! The earlier config you sent had the config for `MMM-Screencast` outside the modules array: `modules: [ <place all module config objects here> ]`. 

Good luck!
