### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by philstue** [kevinatown/MMM-Screencast#23]
Hey guys, 

i installed the screencast module and after trying to start a stream on youtube-app with my iphone
i am running in an error.

"A JavaScript error occured in the main process.
TypeError: Cannot read property "x" undefined at Positioner.move(./MMM-Screencast/node_modules/electron-positioner/index.js:113:44)"

" magicmirror-screencast@0.0.3 start /home/pi/MagicMirror/modules/MMM-Screencast
> electron app.js "http://www.youtube.com/tv?pairingCode=1C43B3CD-7784-4110-A9BA-8D2E8839B250&rUrl=ws%3A%2F%2F192.168.4.31%3A49466%2F2D6328E1-2043-463C-99C3-41B2CCA3A78C&rId=F2421513-EF4B-4224-84E2-84F76F865078&theme=cl&launch=dial-watch" "bottom_right" "500" "300"

screencast stdout: starting server on  /tmp/MMM-Screencast.screenCastWindow

screencast stdout: starting TLS server false

screencast stdout: starting server as Unix || Windows Socket"

Does anyone know a solution?

**Comment by kevinatown** [comment]
Hey @philstue, so it looks like you might of configured the module incorrectly. Can I see an example of your `config.js`?

It looks like `config.position` should be one of `['bottomRight', 'bottomCenter', 'bottomLeft', 'center', 'topRight', 'topCenter', 'topLeft']` you provided `bottom_right`.

**Comment by philstue** [comment]
my mistake. 

it works now!! you were right.

Thanks for your help.

**Comment by kevinatown** [comment]
No worries. Enjoy!
