### ISSUE TITLE
Casting from chrome?

### ISSUE THREAD

**Issue by anthonyfish** [kevinatown/MMM-Screencast#28]
Thanks for this amazing module. Everything works out of the box and I am able to cast from my phone's YouTube app. But I can't seem to cast from chrome using the cast extension from desktop connecting to the same network. I wonder if casting from chrome is fundementally different from cast from phone?

**Comment by kevinatown** [comment]
Hey! @anthonyfish Thanks for reaching out. This module was implemented using the Discovery and Launch Protocol and I believe chrome uses a different protocol. Unfortunately, I have not had time to look into and implement other protocols and build out more support. Hopefully, I will get sometime.

As theres not much I can do about this now, I am going to close this issue. Thanks again!
