### ISSUE TITLE
Not running... possible error during install

### ISSUE THREAD

**Issue by CaptainSteve** [kevinatown/MMM-Screencast#3]
First off, I'm new to Raspberry Pi and haven't had any real computer training.
So this may or may not be an easy fix, but I believe there's maybe 1 or 2 issues during installation. I've attached a copy of my install for your reference (with the 2 areas marked for ease of locating).
I'll attach the copy/pasted files from during the install and the log.log file I created from reading the other issues you've responded to.
No issue with running MagicMirror. Everything works fine and I've removed and re-installed the Screencast a couple times - same install result. The Screencast doesn't appear on the MagicMirror, nor does it show up on my youtube app as a casting option.
I'm on the same wifi with my Pi and my Iphone - does it work with iphone? 
I appreciate your help!
[log.log](https://github.com/kevinatown/MMM-Screencast/files/1415090/log.log)
[screencastInstall.log](https://github.com/kevinatown/MMM-Screencast/files/1415091/screencastInstall.log)

**Comment by kevinatown** [comment]
Hey thanks for these logs, they are always really helpful to determine what could be going wrong. Also I am sorry that it is not working correctly for you. However, it seems like everything was installed correctly and the casting server started normally, `DIAL Server is running on PORT 8569`. And yes this should work with an iPhone (I have one and it works). I am going to ask some questions and I am sorry if they seem stupid, or you obviously did it, I would just want to check to ensure that we can get a resolution.
1. What version of iOS and the YouTube app do you have? It could be that you might have to update to use it.
2. Are you able to cast from your iPhone to any other devices, e.g. a chromecast? Kinda the same question, do any other devices show up in the YouTube casting icon?
3. What version of the RasberryPi do you have? If you are not sure type: `cat /proc/cpuinfo` and compare the revision info to the chart found [here](https://elinux.org/RPi_HardwareHistory).
4. When did you initially clone the repo?
5. What other modules are you running?

Other things to try as well:
1. Make sure you have the newest code:
```
cd modules/MMM-Screencast
git pull
npm install
```
2. Run it again with `display=:0 npm start >> log.log`. Let it start up and all modules start. Then ensure your phone is on the same wifi as the pi, open YouTube for a bit, click on the cast icon - do this a couple times. Finally, kill the MM process and send the log.log in this chat. 

3. Try removing other modules one by one and running MM and after starting try opening YouTube and connecting.

Thanks!

**Comment by CaptainSteve** [comment]
Thanks for the prompt reply back, I'll get all the info and such put together and post it later this evening. It may just be an internet/wifi issue to be honest, I'm currently hopping between work internet (mobile/guest/employee types) and "spotty" hotel internet... so let me test it out somewhere else that has clean and simple internet. Then I'll get back to you with the outcome (and info if necessary).
Many thanks!

**Comment by CaptainSteve** [comment]
Still no luck... after many attempts yesterday/lastnight. But for your questions:

iOS version 11.0.3 and YouTube version 12.41.13 (both up to date)

I've never used casting before (no Chromecast or Apple tv), and nothing pops up in the casting menu. **I do get the "raspberrypi" when connected to it via bluetooth, but only because BT

RaspberryPi version a02082  (Q1 , 2016)

I initially cloned the repo last weekend. I believe it was Saturday or Sunday.

Currently running only default modules and trying to run Screencast. The default modules I'm using are the Alert, UpdateNotification, Clock, Calendar, Compliments, CurrentWeather, WeatherForecast, and Newsfeed.

I tried your other recommendations, but still no success. I've attached the log.log file for your review as requested.

Like I said before, I'm new to this. So I don't know if this is relevant or not but I'm using "pm2" as an auto start function. I find it hard to believe that could be the problem, but I figured I should let you know just in case. Is there any settings I need to alter on the Pi itself in the sudo raspi-config area? I've been using the VPN but don't know if there are other settings I should enable/disable

Sorry for the lengthy reply, but thanks again for your help!

**Comment by kevinatown** [comment]
Oh man, you got a real winner here, so lets try some more troubleshooting. 
1. Can I see a copy of the `config.js` file? Also can I see the `run-start.sh` file it looks like you are using to start your MM. Just making sure everything there looks alright.
2. What exactly do you mean when you say you are using the VPN? Can you point me to the vpn you are using and the steps you took? This could very well be it but I'm not sure. 
3. Let's check the ports of the pi and make sure that they are all open like they should be. With the MM running, type: `netstat -lptn` and paste the outcome here.

Also if there is anymore information about what you did to set up the pi, like anything else you added on it or anything else about the network you are on could help solve this. Sorry, we haven't gotten to the bottom of this yet.

Thanks!

**Comment by CaptainSteve** [comment]
Ok I'll get that info together and post it later this evening. Interestingly enough though, I managed to get it working on an old ipad I had laying around (2nd gen: iOS and youtube are version "9.something") 

So idk if there is a difference in casting protocol/format, but I've been mistaking the "airplay" icon as the "casting" icon on my phone. So I DO have the casting button on my older ipad, but I do NOT have the casting button appearing on my iPhone-youtube app; I.e. casting button on old ipad works, airplay button on iphone looks for apple tv and nothing shows up. I don't know if it uses a different protocol/format to "cast" (like I believe chromecast uses 'DIAL' or something in that area)

Also, sorry for the typo on my part but I meant VNC (not VPN).*

So I'll run all the commands and attach the info you've requested later tonight, but to me it seems the issue is coming from the "newer" version of youtube (no casting button/icon). Yet I have the cast button on the older version I have on my ipad. 

My apologies for the goose chase and misinformation earlier

**Comment by kevinatown** [comment]
Hey, so that was a good idea to check another device and because it worked and appeared on your iPad, everything is working as it should. You do not need to send you `config.js`, `run-start.sh`, or the results of the `netstat` call, as everything is find with the setup on the pi. 

The issue I believe is with either your phone or the network that you are on. The newest version of the YouTube app is supported and has been tested with MMM-Screencast (I have it on my phone). I would attempt to uninstall and reinstall the YouTube app on your phone. As for the potential network issue, be sure that both the pi and your phone are in areas that are close to the router and that their signals are strong. Also if you have any information about your network set-up and the location of the MM as compared to the router this might help.

Good Luck!

**Comment by CaptainSteve** [comment]
Roger that. I appreciate all the help with this.

I have no doubt I'll get it all squared away once I get home and can use something other than hotel wifi or my work's wifi.

Awesome job on the module and thanks again for all the help with troubleshooting. Definitely was a good learning experience for me!
-Steve
