### ISSUE TITLE
[Feature Request] Send notifications

### ISSUE THREAD

**Issue by moryoav** [kevinatown/MMM-Screencast#31]
It would be great and maybe not too difficult if this module would send some notifications when YouTube window is created/closed. This would allow more complex interactions, such as hiding certain modules when the YouTube window is open to prevent clutter.

**Comment by kevinatown** [comment]
Hey @moryoav, this is a great idea. If/when I find sometime I'll try to implement this. Thanks!

**Comment by kevinatown** [comment]
@moryoav closing this issue as the feature should be done now. Please pull and reinstall dependencies to get the feature.
