### ISSUE TITLE
not work with MM 2.1.3

### ISSUE THREAD

**Issue by nojoom4000** [kevinatown/MMM-Screencast#4]
Hi Dear 
Can you update this Module
cause not work with the last version of MagicMirror

**Comment by kevinatown** [comment]
Hi Nojoom, sorry about the delay. I updated the node_helper to work with the latest version of MM. Please pull the new code:

```
cd modules/MMM-Screencast/
git pull
```

Let me know if there are any other issues you see. Enjoy!
