### ISSUE TITLE
Module not working anymore

### ISSUE THREAD

**Issue by the7reek** [kevinatown/MMM-Screencast#41]
when trying to cast, a window opens that says that this version of youtube doesn't work with this device anymore and goes to youtube homepage.

**Comment by everybodyfloats** [comment]
I am experiencing this issue as well. It was working last week...

**Comment by samsnv** [comment]
Hi friends,whats this new problem!! {the youtube app on this device is no longer available}??

**Comment by kevinatown** [comment]
Hi y'all, 

So it looks like youtube pulled the plug on their open platform tv, which MMM-Screencast was using. I am currently working on a fix, but not sure when I will have it done. Sorry about the inconvenience.

**Comment by samsnv** [comment]
thank you Kevinatown and good luck...

**Comment by pociorotto** [comment]
Ciao Kevinatown..Scrivo dall'Italia....Spero tu posso ripristinare il modulo...Era molto interessante

**Comment by kevinatown** [comment]
Hi all! Sorry about the delay on this, been swamped at work and the fix I had in mind turned out to be a lot more involved than I thought. I'm still working on it tho and will keep y'all in the loop on my progress.

**Comment by Podgrade** [comment]
Hi Kevin,

the browser of my Samsung TV for example is still able to call the YT/tv page. 
To costumize the headers of the requests could be a possible workaround.

I am going to play around and see if I can help out.

**Comment by kevinatown** [comment]
@Podgrade i like it. So YouTube quit YouTube tv to “force” users to access it through other sources. I’ve been attempting to get a small android TV up and running, but so far to no luck. 

I do like this take: somethings to keep in mind tho:
* I don’t know if YouTube took their deployed yt tv down or are just routing traffic based on the headers
* if it’s still up, I’m pretty sure there’s a way to override default headers within the electron app.
* if not you might have to find an archived version of the yt tv app.

I haven’t had much luck with the yt tv and have been extremely busy with work. Let me know if there’s anything that I can do to help ya out and I’ll try to make time to run at this latter in the week.

Thanks!

**Comment by Podgrade** [comment]
@kevinatown yes it is definitively running. They are redirecting everything which is not Apple/Samsung/etc. to the main yt page. 

Try it out with the curl command:


**`curl -L http://youtube.de/tv`** 
**redirects me to the main page**

**`curl -L -A "SamsungBrowser/1.0 (SMART-TV; Linux; Tizen SamsungBrowser/1.0 TV Safari/538.1" http://youtube.de/tv`** 
**leaves me on the tv plattform.**

Since I also have a lot of work, I will have to find time to work on it.
But together we can do it - hopefully :-)

**Comment by kevinatown** [comment]
@Podgrade this is great news! Thank you for finding this! I believe there is or at least _should be_ a way to intercept all requests and add/change headers. I’ll definitely make time to look into this!

**Comment by kevinatown** [comment]
@Podgrade your solution worked like a charm. I also had to add a bit of support for autoplaying on devices as it seems that chromium doesn't like autoplay anymore. 

@the7reek @nadalalyafaie @pociorotto @everybodyfloats @samsnv please pull from the MMM-Screencast directory do the following:

```bash
git pull
rm -rf node_modules
npm i
```

This should solve the issue. Please feel free to reach out/open another issue if there is anything else. Thanks!

**Comment by the7reek** [comment]
Thank you so much!! I'll try this later

Il mar 5 nov 2019, 21:40 Kevin Townsend <notifications@github.com> ha
scritto:

**Comment by Podgrade** [comment]
Great @kevinatown!

I tried it - works like a charm!
Thank you!
