### ISSUE TITLE
problem with electron while installing

### ISSUE THREAD

**Issue by Smiley-94** [kevinatown/MMM-Screencast#44]
I don't know if I should open a ticket here but I don't seem to get the plugin to install, I get this error while installing and I did not found a solution to it, I'm running the latest version of magic mirror on a raspberry p zero w, here is a log of the problem, thank you in advance for your help

```
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead

> electron@3.1.13 postinstall /home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron
> node install.js

Downloading tmp-4511-0-electron-v3.1.13-linux-armv6l.zip
Error: GET https://github.com/electron/electron/releases/download/v3.1.13/electron-v3.1.13-linux-armv6l.zip returned 404
/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron/install.js:49
  throw err
  ^

Error: Failed to find Electron v3.1.13 for linux-armv6l at https://github.com/electron/electron/releases/download/v3.1.13/electron-v3.1.13-linux-armv6l.zip
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:198:13)
    at Request.onRequestResponse (/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.1.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@3.1.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-11T01_30_55_830Z-debug.log
```

<img width="998" alt="error" src="https://user-images.githubusercontent.com/56447924/68554947-81711c80-042b-11ea-8706-380f02eaf6f5.png">

**Comment by kevinatown** [comment]
Hey @Smiley-94! 

Sorry bout this issue, seems like I should have been testing on pi-zero. Theres 2 options for solving this: 

1. update electron in the `MMM-Screencast/package.json` to a supported version for `linux-armv6l`. According to their [releases](https://github.com/electron/electron/releases/tag/v7.1.1) `7.1.1` should work. 
2. Remove electron from the package completely and just install it (once again from the MMM-Screencast dir).
something like:
```bash
npm install --arch=armv7l
npm install electron
```

Also on a side note, you shouldn't use `sudo` for installing packages, there could be some unforeseen consequences by giving all packages to root.

This should solve your issue. LMK if you need anymore help and feel free to reopen this issue!
