### ISSUE TITLE
Change "raspberrypi" on Screencast menu

### ISSUE THREAD

**Issue by jag-k** [kevinatown/MMM-Screencast#47]
How to change "raspberrypi" on screencast menu?

**Comment by kevinatown** [comment]
Hey @jag-k! So I just left the default hostname for that screencast menu, so you can simply change the hostname of your pi to whatever. But, I will also implement a config so that you don't have to change your pi's name.

Look for the change here this week/weekend.

**Comment by williamsollin** [comment]
It would be amazing if that was a config option!

**Comment by LeviDavisCode** [comment]
hi, I was wondering how I could change it in the config?

**Comment by kevinatown** [comment]
Hey sorry y'all, been on vacation and just getting back in the swing of things. I have made some changes and will try and merge get them merged.

**Comment by kevinatown** [comment]
Hi @LeviDavisCode @jag-k @williamsollin so now you should be able to change the names in the config. please see the readme for the new updated configs. Thanks!

**Comment by jag-k** [comment]
:kissing_heart::kissing_heart::kissing_heart::kissing_heart::kissing_heart::kissing_heart:
