### ISSUE TITLE
Does not run under Windows

### ISSUE THREAD

**Issue by Kiina** [kevinatown/MMM-Screencast#5]
Basically the current version crashes when starting npm:

```
Whoops! There was an uncaught exception...
{ Error: spawn npm ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs:
   [ 'start',
     'http://www.youtube.com/tv?pairingCode=',
     'bottomRight',
     500,
     300 ] }
```

This can be fixed if you change how to spawn npm:

```
child = spawn('npm', ['start', url, config.position, config.width, config.height], {
  cwd: 'modules/MMM-Screencast', shell: true
})
```

But after that the real problems start:

```
screencast stdout:

screencast stdout: Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.screenCastWindow

screencast stdout: starting server on  /tmp/app.screenCastWindow
starting TLS server false

screencast stdout: starting server as Unix || Windows Socket

screencast stdout: server error { Error: listen EADDRINUSE \\.\pipe\tmp-app.screenCastWindow
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1247:19)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1413:5)
    at Server.startServer (C:\MagicMirror\modules\MMM-Screencast\node_modules\node-ipc\dao\socketServer.js:315:21)
    at FSReqWrap.oncomplete (fs.js:114:15)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '\\\\.\\pipe\\tmp-app.screenCastWindow',
  port: -1 }
```

**Comment by kevinatown** [comment]
Hi Kiina, yes currently MMM-Screencast doesn't work on windows systems. It was developed for UNIX based systems. I can try to fix these issues, but might be a little bit of time. Sorry for this inconvenience.

**Comment by Kiina** [comment]
Yeah not sure how many people run their MagicMirror on a full Windows box, so maybe I'm the only one with the problem.

**Comment by kevinatown** [comment]
Hey Kiina, sorry about the delay. There's not many people that use MM on a windows machine. I think I know the issue has to do with the interprocess communication between the DIAL server and the electron app thats running the youtubeTV app. I'll keep this issue open and hopefully will have time to fix this issue. Sorry about the delay in fixing this!

**Comment by kevinatown** [comment]
Het @Kiina sorry for the extremely late resolution, but if you pull the latest version and reinstall the node_modules you should be able to run it on a windows. Like so:
```
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
```
I am going to close this issue, but feel free to reopen it if you have any issues.

Thanks,
Kevin

**Comment by Kiina** [comment]
Working great, thank you!

**Comment by businessclimber** [comment]
Hi

I am getting an error while install MMM-Screecast module. The following error comes when i install npm. I am using Raspberry pi 4. 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@6.0.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@6.0.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I tried installing npm through the following command.
sudo npm install --unsafe-perm=true --allow-root

but it showed 11 vulnerabilities. I could see the hostname while casting but it doesnt connect.

Please help!
