### ISSUE TITLE
can't get it work

### ISSUE THREAD

**Issue by Yuhan-1in** [kevinatown/MMM-Screencast#51]
this happened when I try npm install. I added the config. My mirror is working but I can't cast my video.

audited 369 packages in 8.494s

1 package is looking for funding
  run `npm fund` for details

found 11 vulnerabilities (5 low, 2 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MagicMirror/modules/MMM-Screencast $ npm fund
magicmirror-screencast@0.0.5
└─┬ resolve@1.14.2
  └── url: https://github.com/sponsors/ljharb

**Comment by kevinatown** [comment]
Hey @Yuhan-1in! nothing looks out of the ordinary with the logs you put. Can you do the following:
- attach a copy of you config.js (with all api keys removed)
- send me some more logs by doing the following:
```bash
display=:0 npm start >> log.log
```
- let the MM run for a bit, then kill it, and finally sending me that file `log.log`.
- Also what other modules are you using?

Thanks!

**Comment by Yuhan-1in** [comment]
Hi @kevinatown,
I can't get the log to work. It showed me this when I use the command you gave me.
here is full my config and I also attached the log from the npm error. Thank you!
[config.txt](https://github.com/kevinatown/MMM-Screencast/files/4065101/config.txt)
[log.txt](https://github.com/kevinatown/MMM-Screencast/files/4065118/log.txt)

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/pi/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-15T13_20_38_024Z-debug.log
```

**Comment by Yuhan-1in** [comment]
I don't know what happened but I update my pi again and it works now. Thank you

**Comment by kevinatown** [comment]
Haha some times that's all that is needed. Enjoy :)
