### ISSUE TITLE
Position Issue

### ISSUE THREAD

**Issue by Mert4531** [kevinatown/MMM-Screencast#52]
Hi there
First of all this module is really good. I have a little problem 
I want to change the position of the screencast window to lower_third. However this module position settings don't have lower_third position. 
Is there any other method of setting this module to lower_third position?

**Comment by kevinatown** [comment]
Hi @Mert4531, so there really isn't a `lower_third`, the current options are: `'bottomRight', 'bottomCenter', 'bottomLeft', 'center', 'topRight', 'topCenter', 'topLeft'`. You could potentially use either `bottomeCenter` or `bottomLeft` and set the width to achieve a `lower_third` position. 

If this doesn't work, I was going to implement a more direct positioning config, where you can give the x,y coordinates to position.
