### ISSUE TITLE
ScreenCast blocks all other modules

### ISSUE THREAD

**Issue by guschavez** [kevinatown/MMM-Screencast#59]
So I am loving ScreenCast but the one major issue I have is whenever I add it to my MM it works fine but I can no longer see any other module the screen is all black until I play a video then I can see just the video and no other module. It is set bottom center and is small enough that it should not be blocking other modules at all. Any idea where I can start looking into to this? I am pasting my whole config file in here in case that helps.

### > /* Magic Mirror Config Sample
>  *
>  * By Michael Teeuw http://michaelteeuw.nl
>  * MIT Licensed.
>  *
>  * For more information how you can configurate this file
>  * See https://github.com/MichMich/MagicMirror#configuration
>  *
>  */
> 
> var config = {
> 	address: "localhost", // Address to listen on, can be:
> 	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
> 	                      // - another specific IPv4/6 to listen on a specific interface
> 	                      // - "", "0.0.0.0", "::" to listen on any interface
> 	                      // Default, when address config is left out, is "localhost"
> 	port: 8080,
> 	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
> 	                                                       // or add a specific IPv4 of 192.168.1.5 :
> 	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
> 	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
> 	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
> 
> 	language: "en",
> 	timeFormat: 12,
> 	units: "imperial",
> 
> 	modules: [
> 		{
> 			module: "alert",
> 		},
> 		{
> 			module: "updatenotification",
> 			position: "top_bar"
> 		},
> 		{
> 			module: "clock",
> 			position: "top_left"
> 		},
> 		{
> 			module: "calendar",
> 			header: "Gus & Frances",
> 			position: "top_left",
> 			config: {
> 				calendars: [
> 					{
> 						symbol: "calendar-check",
> 						url: "https://calendar.google.com/calendar/edit/out/this/info"
> 					}
> 				]
> 			}
> 		},
> 		{
> 			module: "compliments",
> 			position: "upper_third"
> 		},
> 		{
> 			module: "currentweather",
> 			position: "top_right",
> 			config: {
> 				location: "South",
> 				locationID: "5315313",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
> 				appid: "5fae65978619cf47aa1ea4de3e980e23"
> 			}
> 		},
> 		{
> 			module: "weatherforecast",
> 			position: "top_right",
> 			header: "Weather Forecast",
> 			config: {
> 				location: "South",
> 				locationID: "5345313",  //ID from https://openweathermap.org/city
> 				appid: "5fae65978619cf47aa1ea4de3e990e23"
> 			}
> 		},
> 		
> 	]
> }
> var config = {
>     modules: [
>         {
> 		module: 'MMM-Screencast',
> 		position: 'bottom_center', // This position is for a hidden <div /> and not the screencast window
> 		config: {
> 			position: 'bottomCenter',
> 			height: 300,
> 			width: 500,
> 		}
>         }
>     ]
> }
> /*************** DO NOT EDIT THE LINE BELOW ***************/
> if (typeof module !== "undefined") {module.exports = config;}

**Comment by kevinatown** [comment]
Hey @guschavez! So the issue here is that you are overwriting your config object with an object that only has the MMM-Screencast module. Notice the other `var config = ` (this is where you overwrite it). What you should do is just add the MMM-Screencast config to the object after the weatherforecast module config.

You can try this config instead:
```javascript
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
  address: "localhost",
  port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], 
  language: "en",
  timeFormat: 12,
  units: "imperial",
  modules: [
    {
      module: "alert",
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "clock",
      position: "top_left"
    },
    {
      module: "calendar",
      header: "Gus & Frances",
      position: "top_left",
      config: {
        calendars: [
          {
            symbol: "calendar-check",
            url: "https://calendar.google.com/calendar/edit/out/this/info"
          }
        ]
      }
    },
    {
      module: "compliments",
      position: "upper_third"
    },
    {
      module: "currentweather",
      position: "top_right",
      config: {
        location: "South",
        locationID: "5315313", //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
        appid: "5fae65978619cf47aa1ea4de3e980e23"
      }
    },
    {
      module: "weatherforecast",
      position: "top_right",
      header: "Weather Forecast",
      config: {
      location: "South",
      locationID: "5345313", //ID from https://openweathermap.org/city
      appid: "5fae65978619cf47aa1ea4de3e990e23"
    },
    {
      module: 'MMM-Screencast',
      position: 'bottom_center',
      config: {
        position: 'bottomCenter',
        height: 300,
        width: 500,
      }
    },
  ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```


Let me know if you have any issues!

**Comment by kevinatown** [comment]
Closesing as no response, but feel free to reopen this issue if this problem persists or open another issue if something arises.
