### ISSUE TITLE
Lower the resolution

### ISSUE THREAD

**Issue by sainiaj** [kevinatown/MMM-Screencast#6]
Hi is it possible to lay using 240p perhaps 
reason being i am using pi 3 and after launching this module (conenction  via youtube app) 
free memory goes below 3% and ended up crashes 
at the moment 

                module: 'MMM-Screencast',
                position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
                config: {
                        position: 'center',
                        height: 240,
                        width:320,
                }
        },

**Comment by sainiaj** [comment]
Hi yes I am using about 10 modules total plus google pi home assistant

**Comment by kevinatown** [comment]
Hey, So after doing some research there is no way that I can actually lower the resolution of the videos, as it is controlled by the youtube app. Is there any other modules that are using a lot of memory?

**Comment by sainiaj** [comment]
How can I check
Module based

I have google assistant
Weather clock calender atm news feed,
Sechduler which shows in the morning only map of highway as well time to
work and sunsign

Free memory usually around 20 system load 1.5ish

I can send you the log
Everytime I play youtube it crashed the UI but keeps playing youtube in the
background
And I have to manually shh and Sufi reboot then

**Comment by kevinatown** [comment]
Yea a log will be great. There is def. some issue. However I do not know if its with the module, since that's still playing and it crashes the app. So any information you can give will be great. You can watch the cpu and memory while you run the app and cast to it. Try these and send me the logs:

Run the cpu/memory watch:
```
top -b -o %MEM > topMemory.txt
```

```
top -b -o %CPU > topCPU.txt
```
