### ISSUE TITLE
Casting different formats QUESTION

### ISSUE THREAD

**Issue by Bernard-h** [kevinatown/MMM-Screencast#61]
Would it be difficult to get this working on Netflix / Ziggo / HBO / Disney ?

**Comment by kevinatown** [comment]
So sadly it's not trivial. I've spent sometime looking into netflix but have yet to have gotten it to work and then work, life, other projects come up and i loose track of where I was. I'll try to find time to open this up again.

Also I'm going to close this ticket as it's a duplicate of #27
