### ISSUE TITLE
this project seems to be forgotten about

### ISSUE THREAD

**Issue by shotbyapony** [kevinatown/MMM-Screencast#69]
can someone take over development?

**Comment by kevinatown** [comment]
Hey @shotbyapony! This project isn't forgotten about, but as a free and open source project it isn't my number one priority and comes behind life, work, and other projects at times. 

I could always use some help by: 
- answering issues
- keeping track of feature requests
- mapping out development
- developing some code

Feel free to help - and thanks for your interest in this project!
