### ISSUE TITLE
Changing the position

### ISSUE THREAD

**Issue by drk-geek** [kevinatown/MMM-Screencast#71]
I would like to change the position from "bottomRight" to center of mirror, please advise syntax to use
Thanks

**Comment by kevinatown** [comment]
Hey @drk-geek, please see the following excerpt from the [readme](https://github.com/kevinatown/MMM-Screencast/blob/master/README.md):

| Option    | Description
|---------- |-----------
| `position`| *Required* The position of the screencast window. <br>**Options:** `['bottomRight', 'bottomCenter', 'bottomLeft', 'center',  'topRight', 'topCenter', 'topLeft']` <br>**Type:** `string` <br>**Note:** This module config actual sets the location, not the magic mirror position config.

Thanks!
