### ISSUE TITLE
Screen Mirrored successfully but without sound

### ISSUE THREAD

**Issue by aryanarora2000** [kevinatown/MMM-Screencast#75]
Hi there, I am a student and was just mingling around with a raspberry pi when I decided to create a magic mirror. I followed all the steps and was able to cast via youtube the only problem is that there is no output of sound. I am using an old LCD TV and only when I try to cast I am not able to get an audio output. Kindly help me out

**Comment by Dmitchell94** [comment]
I am also unable to get sound while other modules can still play sound

**Comment by Dmitchell94** [comment]
While this is also affecting me this issue appears to be a duplicate of #54

**Comment by kevinatown** [comment]
@aryanarora2000 this does seem to be potentially and duplicate of #54. Can you please also provide some more information about how you are connecting to the old LCD TV and what device/version/os you are using? My guess is there is prob some missing config needed. 

Also I am going to close this issue, but please do continue in #54
