### ISSUE TITLE
cast window position

### ISSUE THREAD

**Issue by khullarmudit** [kevinatown/MMM-Screencast#77]
Hi 

Not sure if this is even a possibility, but is there a way in the config where I can specify the actual window location for the casted content. Right now I'm using the default config for the case, and though it works perfectly, because it will stay on top, it tends to cover up my newsfeed (bottom_bar). Unfortunately due to the size of the screen I'm using, lowering the pixel count for the display area is not really an option.. 

Is there a possibility to, perhaps, identify a location to offset the display window from the regular bottomLeft to let's say 20 pixels from the edge on both left and bottom of the display? 

Thanks

**Comment by kevinatown** [comment]
Hi @khullarmudit, so I thought I had actually did this a while back, but it seems as if I dropped this and forgot working on it. I will try and get back to it.

**Comment by mawoka-myblock** [comment]
@kevinatown please do it. I have the same issue but it is a very good Module, but please go on working on this module!
