### ISSUE TITLE
[Question] Is there any possibility to point sound on exact sink ?

### ISSUE THREAD

**Issue by mihanich** [kevinatown/MMM-Screencast#86]
Hi @kevinatown . 
First of all - THANK YOU! - for all work you've done!

I got asus tinker board s and set up MMM, Google Assistant and configure asound as well to point all sound to D2 sink. and all (even system notifications) pointed to 3.5 (which D2) (as well it is set as default everywhere). Except Screencast instance. Pulseaudio server is up and running right, in pavucontrol there is no screencast instance and still got no sound from playing video... 
I believe if I got direction where to point sound sink for screencast - it would work.

Can you please clarify - is there any possibility to point sound somehow to some particular sound sink?

Thank you.

**Comment by kevinatown** [comment]
Heyo! Thanks @mihanich. Sorry about the late response, a lot has been going on lately :(

 So short answer is yes, there is a way to configure where to point the sound, however it's not really tied to MMM-Screencast, but to the chromium instance being used by electron. So some questions are:
- what OS are you using on your tinker board?
- how did you go about setting the sound for Google Assistant and MMM?

**Comment by mihanich** [comment]
Hey @kevinatown! long responces is my speciality)))
sorry about that.
I've just realize that question is not relevan due to another way of configuration which was rebuilt several monthes ago.
so how I resolve pointing of sound without of pointing:
1. on clean install with pulseaudio install all my software.
2. remove all hard-points to sinks
3. play around with timing of services (software) to start and set timouts in screepts (all soft start after desktop, pulse and ui start) - this will garatee that sound system already available to work correct
4. set correct sinks in pavucontrol

Maybe this will help somebody in future.
Thank you @kevinatown )

closing as not actual anymore.

**Comment by kevinatown** [comment]
Wonderful! @mihanich thank you so much for leaving how you were able to solve your issue!
