### ISSUE TITLE
Use notifications to close?

### ISSUE THREAD

**Issue by cluelesscarter** [kevinatown/MMM-Screencast#88]
Hey,

I'm using a gesture sensor and I use it to issue notifications to MM os for things like "PAGE_INCREASE" for mm-pages or "ASSISTANT_CLEAR" for mm-GoogleAssistant...

Would it be possible to get a notification to cancel the cast?

**Comment by kevinatown** [comment]
Hey! @cluelesscarter yes this was requested in #31 but I haven't had time to finish the notifications (I'm currently like 80% there but haven't had the time to work on it since the spring. I'll see if I get some time to get back to it. 

Also closing this as it's a dup.
