### ISSUE TITLE
Javascript Uncaught Exception when attempting to cast

### ISSUE THREAD

**Issue by sobrien556** [kevinatown/MMM-Screencast#9]
Hello, thank you for the module! I have pasted my config info down below. Every time I attempt to cast to the mirror I receive an Uncaught Exception error message. I attached a screenshot of the issue below. Is this a known issue or have you run into this before? Please let me know if there is a solution, thank you!

{
	module: 'MMM-Screencast',
	position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
	config: {
	position: 'bottomright',
	height: 300,
	width: 500,
	}
},

![capture](https://user-images.githubusercontent.com/36823738/36645351-3d0402a6-1a35-11e8-9fc8-6400baf5972b.JPG)

Edit: Also, i'm not sure if this helps, or has anything to do with the issue, but here is the screenshot from when I installed the module..

![capture2](https://user-images.githubusercontent.com/36823738/36645476-8881b7da-1a37-11e8-85f1-3b70e665e714.JPG)

**Comment by kevinatown** [comment]
Hey sobrien556,

So this is the first time I have run into this issue. Do you think you can provide me with a complete copy of your `config.js`? Also what environment are you using this on?

**Comment by Krijbolder** [comment]
I have the same problem. 
I'm streaming a youtube fie from Iphone to Pi. Nothing happen, black screen. Hope you can help.

**Comment by sobrien556** [comment]
I am running on linux and I have attached my config.js file below!
[config.txt](https://github.com/kevinatown/MMM-Screencast/files/1772557/config.txt)

**Comment by kevinatown** [comment]
Hey, @sobrien556 try changing the inner position (i.e. the position in the config object) to camel case `bottomRight`. Like so:
```
	module: 'MMM-Screencast',
			position: 'bottom_right',
			config: {
			    position: 'bottomRight',
			    height: 300,
			    width: 500,
		     }
        	},
```
Let me know if this helps.

**Comment by kevinatown** [comment]
Also @sobrien556, Try pulling the newest version of `MMM-Screencast` like so:

```
# from the MagicMirror dir
cd modules/MMM-Screencast/
rm -rf node_modules/
git pull
npm install
```
Then try running the MM again. Let me know if this helps!

Thanks,
Kevin

**Comment by kevinatown** [comment]
Closing this issue, feel free to re-open it/open another issue.

**Comment by bommel947** [comment]
Can you re-open the issue?

Screencast was working initially. But suddendly it stops with the same java exception when trying to cast any video.
I have pulled and installed the latest version from git

npm version: 5.6.0
nodejs: 9.11.2

My Screencast config:

{
        module: 'MMM-Screencast',
        position: 'bottom_right', // This position is for a hidden <div /> and not the $
        config: {
            position: 'top_center',
            height: 600,
            width: 800,
        }
},

Any help is very much appreciated!

**Comment by kevinatown** [comment]
Hey @bommel947 this was an issue with the config, Theres two positions in the config for MMM-Screencast note that the inner config's portion is for the actual cast window and accepts a value of: `['bottomRight', 'bottomCenter', 'bottomLeft', 'center', 'topRight', 'topCenter', 'topLeft']` (items are camel cased look [here](https://github.com/kevinatown/MMM-Screencast)). Also since this was a very specific issue its not right reopening this issue.

If you have more problems after changing the inner config please feel free to open a new issue and provide the errors and your config.

Good luck!
