### ISSUE TITLE
Can't seem to Center Module

### ISSUE THREAD

**Issue by r4zi3lrrr** [kevinatown/MMM-Screencast#94]
Hey Guys,

Module seems to work really good, but can't for the life of me get it centered so it launches in a small window.

It seems to launch in full screen. 

My config is below, if someone can please help.

},
	{
    
		module: 'MMM-Screencast',
		position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
		config: {
			position: 'center',
			height: 300,
			width: 300,
		}

**Comment by kevinatown** [comment]
Hey @r4zi3lrrr! Sorry to hear you are having issues completely centering it. You can try to update MMM-Screencast and use the `x` (Window's left offset from screen.) and `y` (Window's top offset from screen.) config properties to get it exactly where you want it. It might take sometime playing around with it until you get a good position. 

Also, another idea might to be to use a rectangle thats matches the monitor or [video resolution](http://cdn.techgyd.com/terms.png). As it could be that a 300x300 square doesn't fit nicely.

**Comment by r4zi3lrrr** [comment]
Thank you - will give it a go.
