### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by avanloo01** [kevinatown/MMM-Screencast#96]
I've got 12 vulnerabilities upon installing the module, but I don't know how to fix them. Can anyone help?

**Comment by kevinatown** [comment]
Hey @avanloo01! I am assuming you're running this just on you home network, correct? If so you _probably_ don't need to worry about the vulnerabilities. However, if you still don't like the fact that there are there you can run (in the MMM-Screencast dir) `npm audit fix` -- this may, however break MMM-Screencast, cause I haven't looked into the needed updates yet. I'll see about doing that for this module soon.

Also closing this comment as it's not the biggest deal for most use cases of MMM-Screencast.
