### ISSUE TITLE
The Magic Mirror does not show on  my YouTube 

### ISSUE THREAD

**Issue by dhmy1717** [kevinatown/MMM-Screencast#99]
hello there,

the MagicMirro does not show up on my YouTube to cast it !!

config and insall been done but stii does not show up !!

what may i do  to solve it ?

appreciated ,

**Comment by smartthinks** [comment]
@dhmy1717 I just figured out the problem module can be the Mmm-AlexaControl.

**Comment by mobious25** [comment]
If you put the AlexaControl after Screencast in the config file, it works.

**Comment by kevinatown** [comment]
Closing as @mobious25 seems to have figured out a workaround. Thanks!
